export const CONFIG = {
  privKey: process.env.NSEC,
  pubKeyHex: process.env.PUBKEY || "",
  relays: (process.env.RELAYS && process.env.RELAYS.split(",")) || [
    "wss://relay.damus.io",
    "wss://relay.snort.social",
    "wss://relay.primal.net",
    "wss://relay.nostr.band",
  ],
  kindRequest: 22068,
  giftWrapKind: 21169,
  requestRumorKind: 68,
  responseRumorKind: 69,
  kindResponse: 22069,
  httpPort: Number(process.env.PORT) || 3000,
  mintUrl: process.env.MINT_URL,
  serviceName: process.env.SERVICE_NAME || "NRPC Backend Service",
  serviceAbout:
    process.env.SERVICE_ABOUT || "Remote Procedure Call server over Nostr.",
  servicePicture: process.env.SERVICE_PICTURE || "",
  serviceBanner: "",
  lud16: process.env.LUD16 || "",
  website: process.env.WEBSITE || "",
  nip05: process.env.NIP05 || "",
};
